### ISSUE TITLE
[chart/redis-ha] prometheus annotations conflict

### ISSUE THREAD

**Issue by kfirfer** [DandyDeveloper/charts#101]
The prometheus annotations on the pods is conflicting if using servicemonitors.monitoring.coreos.com 
And prometheus will scrape twice and grafana dashboards shows conflicts

Here:
https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/redis-ha-statefulset.yaml#L32

Need to check also if `exporter.serviceMonitor.enabled` is false, then append the annotations

**Comment by DandyDeveloper** [comment]
@kfirfer Thank you, will jump on this. Should have a turnaround in a few days.

**Comment by eddycharly** [comment]
Hello, is there a grafana dashboard available with all metrics from redis and ha-proxy combined ?
