### ISSUE TITLE
[chart/redis-ha] add more control around update strategy

### ISSUE THREAD

**Issue by cschockaert** [DandyDeveloper/charts#103]
Hello can you add in your redis-ha-statefulset.yaml this ability to control the upgrade mechanism

 (could be tricky sometime to upgrade our redis sentinel cluster in production when we want to control WHEN each pod is restarted)

OnDelete / RollingUpdate

thanks

**Comment by cschockaert** [comment]
@DandyDeveloper i can submit you this MR if you want

**Comment by DandyDeveloper** [comment]
I thought we had this. Would welcome a PR. If not I can do it.
