### ISSUE TITLE
[chart/redis_ha][REQUEST] Add PodDisruptionBudget to HAProxy instances

### ISSUE THREAD

**Issue by a-mantha** [DandyDeveloper/charts#105]
**Is your feature request related to a problem? Please describe.**
Currently you can manage a PodDisruptionBudget for the redis statefulsets, but not for the HA Proxy deployment. As a result, even though the redis backend will be kept HA during a maintenance task, it is possible to cause the HA Proxy service to become temporarily unavailable.

**Describe the solution you'd like**
Add an additional PDB for the HA Proxy deployment. 

**Describe alternatives you've considered**
Currently manually managing the second PDB as part of CI/CD system but it is cleaner to have it all in Helm.

**Comment by DandyDeveloper** [comment]
@a-mantha Good suggestion, I'll add it to my list. Thank you.
