### ISSUE TITLE
[chart/redis_ha][BUG] HAProxy exit-on-failure: killing every processes with SIGTERM

### ISSUE THREAD

**Issue by AbdullahKh** [DandyDeveloper/charts#117]
**Describe the bug**
I'm running version 4.9.3 of the chart, with haproxy enabled.  
HAProxy pods (redis-cluster-redis-ha-haproxy-xxxxxxx-xxxxx) keep restarting:

```
[ALERT] 058/115541 (1) : Current worker #1 (6) exited with code 139 (Segmentation fault)
[ALERT] 058/115541 (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING] 058/115541 (1) : All workers exited. Exiting... (139)
```

```
redis-cluster-redis-ha-haproxy-79f58f7489-bj9tc    1/1     Running   13        40d
redis-cluster-redis-ha-haproxy-79f58f7489-fjxtc     1/1     Running   9          40d
redis-cluster-redis-ha-haproxy-79f58f7489-l7mtc   1/1     Running   4          40d
```

I tried to upgrade to the latest chart 4.12.9, and set haproxy Liveness and Readiness timeout to be 15s,  but I'm still seeing the same behaviour 

**To Reproduce**
1- Install the chart with the default values, except for haproxy.enabled = true

**Comment by DandyDeveloper** [comment]
@AbdullahKh Pretty sure we need to upgrade the HAProxy version, I don't know the exact scenario but upgrading the version does fix this. There's another issue that covers this.

Can you try updating the deployment image version to whatever is latest and let me know if that resolves things for you?

**Comment by maxisam** [comment]
> @AbdullahKh Pretty sure we need to upgrade the HAProxy version, I don't know the exact scenario but upgrading the version does fix this. There's another issue that covers this.
> 
> Can you try updating the deployment image version to whatever is latest and let me know if that resolves things for you?

What version did you try?

**Comment by DandyDeveloper** [comment]
@maxisam I didn't because I haven't experienced this. I was just recommending using a newer LTS tag and letting me know the outcome.
