### ISSUE TITLE
[chart/redis-ha][REQUEST] 

### ISSUE THREAD

**Issue by wsams** [DandyDeveloper/charts#12]
**Is your feature request related to a problem? Please describe.**
Yes, we are unable to use template strings in the `haproxy.customConfig` value. The suggested solution is already applied to `sentinel.customConfig` and `redis.customConfig`.

**Describe the solution you'd like**
I would suggest updating `templates/_configs.tpl` in the `redis-ha` chart. The line,

```
{{ .Values.haproxy.customConfig | indent 4}}
```

could be,

```
{{ tpl .Values.haproxy.customConfig . | indent 4}}
```

It may also be useful to run `haproxy.extraConfig` through `tpl` as well. i.e. `{{ .Values.haproxy.extraConfig | indent 4 }}` changed to `{{ tpl .Values.haproxy.extraConfig . | indent 4 }}`

Thank you

**Comment by DandyDeveloper** [comment]
Fixed in https://github.com/DandyDeveloper/charts/pull/8
