### ISSUE TITLE
[chart/<redis>][BUG] no hostPath in podSecurityPolicy 

### ISSUE THREAD

**Issue by gejunqiang** [DandyDeveloper/charts#127]
**Describe the bug**

According to https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/redis-ha-psp.yaml#L40 ,there is no hostPath volume in podSecurityPolicy. This will cause my redis pod be denied by kubernetes when I use hostPath volume. 

**Expected behavior**
Support hostPath in podSecurityPolicy when user use hostPath.

**Comment by DandyDeveloper** [comment]
@gejunqiang Feel free to make a quick PR if you want, if not. I'll get to it when I can!

**Comment by DandyDeveloper** [comment]
Since PSPs are being deprecated in official K8s and I don't think this is breaking or impacting people. CLosing for now.
