### ISSUE TITLE
[chart/redis-ha][BUG] HAProxy Deployment does not handle Sentinel auth being set

### ISSUE THREAD

**Issue by silvpol** [DandyDeveloper/charts#133]
**Describe the bug**
When Sentinel auth is configured, HAProxy health checks fail and it's impossible to connect to Redis via HAProxy.
Additionally when ONLY sentinel auth is set the chart fails to render.

**To Reproduce**
1. Include the below in values and deploy

```
sentinel:
  auth: true
  password: abc123
```

2. Try to connect to Redis via HAProxy

**Expected behavior**
HAProxy should use configured sentinel auth in checks.

PR with fixes to follow shortly

**Comment by DandyDeveloper** [comment]
@silvpol Keeping an eye out for your PR. Thank you for finding this. 

I assume it was a small mistake in the implementation. I haven't really used auth with Sentinel extensively in my clusters.
