### ISSUE TITLE
[chart/redis-ha-4.5.3][BUG] sha1sum is not defined

### ISSUE THREAD

**Issue by lsp12138** [DandyDeveloper/charts#14]
**Describe the bug**
Error: parse error in "redis-ha/templates/redis-ha-statefulset.yaml": template: redis-ha/templates/redis-ha-statefulset.yaml:107: function "sha1sum" not defined

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by DandyDeveloper** [comment]
@lsp12138 Can you confirm the version of Helm you're running? 

I'm guessing they removed the `sha1sum` in a recent version and I just need to update to use `sha2sum`

**Comment by lsp12138** [comment]
> @lsp12138 Can you confirm the version of Helm you're running?
> 
> I'm guessing they removed the `sha1sum` in a recent version and I just need to update to use `sha2sum`

thanks.
my helm version is `v2.8.2`.
i changed `sha1sum` to `sha256sum` and succeeded.
