### ISSUE TITLE
[chart/redis-ha][BUG] Cannot specify resources for split-brain-fix conainter

### ISSUE THREAD

**Issue by artur-reaboi** [DandyDeveloper/charts#153]
**Describe the bug**
Cannot specify resources for the new split-brain-fix container, part of redis-ha-statefulset. This is required to be able to deploy Redis into namespaces with defined resource quotas.

**Expected behavior**
A way to define container resources for split-brain-fix container.

**Comment by DandyDeveloper** [comment]
@artur-reaboi Adding now.

**Comment by zerkms** [comment]
Right, sorry I initially didn't add it: it consumes little to no resources and I don't run tightly restricted k8s clusters.

**Comment by DandyDeveloper** [comment]
@zerkms No worries. Just an fyi incase your chart uses the old snake case syntax.

**Comment by zerkms** [comment]
@DandyDeveloper I'm switching back to this one as long as I have a spare minute :-)
