### ISSUE TITLE
[chart/redis-ha][BUG] Malformed sentinel id in myid option

### ISSUE THREAD

**Issue by arnediekmann** [DandyDeveloper/charts#16]
**Describe the bug**

When using the latest version `4.5.4` the first sentinel container logs the following error:

```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1
>>> 'sentinel myid f58981a95ae04cab08ae2c2096722429ab8e06bc6a2fda61e1846a90aad7722e'
Malformed Sentinel id in myid option.
```

and the provisioning of the cluster won't go forward as the respective pod is stuck in the status `CrashLoopBackOff`.

**To Reproduce**

I could reproduce the error by installing it via Helm 3 in a Kubernetes cluster with version `1.17.4` with the following command:

```
$ helm install dandydev/redis-ha --version 4.5.4 --generate-name
``` 

**Additional context**

This seems to stem from the fact, that after PR #15 uses SHA256 instead of SHA1 for the ID generation. This makes the ID 64 instead of 40 characters long when hex encoded. The Redis source [seems to have 40 characters hardcoded (at least in 5.0)](https://github.com/antirez/redis/blob/5.0/src/server.h#L109). A fix could therefore trim the encoded SHA-256 to 40 characters in length (e.g. `trunc 40 .theLongHash`).

A workaround for me is to use version `4.5.3` instead.

**Comment by DandyDeveloper** [comment]
@arnediekmann Thank you, I'll get a quick turnaround on this. Been out of action for a week, sorry about the delay.
