### ISSUE TITLE
[chart/redis-ha][BUG] Sentinel liveness check fails with Redis 6.2.6

### ISSUE THREAD

**Issue by bootc** [DandyDeveloper/charts#161]
**Describe the bug**
When using Redis 6.2.6 with `auth` enabled (but not `sentinel.auth`), the Sentinel liveness check always fails.

**To Reproduce**
```
helm install test dandydev/redis-ha --set auth=true --set redisPassword=password --set image.tag=6.2.6-alpine
```
The first of three pod is created and never becomes ready.

**Expected behavior**
Three pods should be created and become ready.

**Additional context**
Redis 6.2.5 work fine.

When running the liveness check by hand, the result is:
```
/data $ /health/sentinel_liveness.sh 
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

The issue is that authentication is enabled when pinging the Sentinel using the auth condition for Redis, rather than checking for `sentinel.auth`:
https://github.com/DandyDeveloper/charts/blob/c3c4e1c8bbe845bad3cc595781b32543cca10cc6/charts/redis-ha/templates/_configs.tpl#L619-L621

**Comment by DandyDeveloper** [comment]
@bootc Thank you. I'll jump on this in the next couple of days. Look like its just a bad conditional in the templates.
