### ISSUE TITLE
[dandydev/grafana-agent][REQUEST] Option to provide our own config map

### ISSUE THREAD

**Issue by davosian** [DandyDeveloper/charts#164]
**Is your feature request related to a problem? Please describe.**
I am trying to use your helm repo to set up a GitOps workflow using flux. Currently, when I deploy your chart, it creates a ConfigMap called which contains a basic configuration for the grafana agent. This configuration needs to be manually adjusted after the helm installation.

**Describe the solution you'd like**
I would like to have a helm value that allows me to specify my own ConfigMap to be used instead. This way I can maintain the grafana agent configuration separately from the installation. 

**Describe alternatives you've considered**
Manually maintaining the configmap after `helm install`. I am also no helm expert, so there might be a standard way to achieve this?

**Additional context**
none

**Comment by DandyDeveloper** [comment]
@davosian On it. Pretty simple change, I'll do that today.
