### ISSUE TITLE
[chart/redis-ha][BUG] Release pipeline failed

### ISSUE THREAD

**Issue by baurmatt** [DandyDeveloper/charts#171]
**Describe the bug**
The pipeline of the last commit failed -> https://github.com/DandyDeveloper/charts/runs/4368680355?check_suite_focus=true

This prohibits users to actually use the CVE fix.

**To Reproduce**
See https://github.com/DandyDeveloper/charts/runs/4368680355?check_suite_focus=true

Try to use 4.14.8

**Expected behavior**
4.14.8 is usable

**Additional context**

**Comment by DandyDeveloper** [comment]
@baurmatt Yeah, I'm aware. Something to do with the secrets in the workflow. 

Sorry I haven't fixed this immediately, I'm the only one working on the repo and have a bunch of other things to maintain haha.

**Comment by DandyDeveloper** [comment]
@baurmatt Problem solved. PAT had expired.

**Comment by baurmatt** [comment]
> Sorry I haven't fixed this immediately, I'm the only one working on the repo and have a bunch of other things to maintain haha.

No worries, I totally understand! :) I just wanted it to be documented in case others stumbled over it.

Thank you for fixing! :)
