### ISSUE TITLE
[chart/grafana-agent][REQUEST] Add additional volume mount configuration

### ISSUE THREAD

**Issue by MurzNN** [DandyDeveloper/charts#172]
**Is your feature request related to a problem? Please describe.**
For many Loki instances there is a requirement to mount system logs directory (eg `/var/log` or systemd's `/var/log/journal`), also container logs (eg `/var/lib/docker/containers`), or any custom log file from hosted node.

But in current Chart I don't see ability to set custom volume mounts to Grafana Agent DaemonSet.

**Describe the solution you'd like**
Will be good to have ability to fill custom folders to mount as volumes for the Grafana Agent pod.

**Comment by DandyDeveloper** [comment]
I still think my grafana agent chart has some merit but I really do need to update it. As such, I'm going to close this for now because option have significantly improved/changed and revisit after I complete the update.
