### ISSUE TITLE
[chart/grafana-agent][REQUEST] Allow enabling debug mode

### ISSUE THREAD

**Issue by MurzNN** [DandyDeveloper/charts#173]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to have debug mode enabled via this line in `agent.yml` file:
```
server:
  log_level: debug
```
But in current chart [there is hardcoded](https://github.com/DandyDeveloper/charts/blob/99f7eaab4a62bef85325100c4c6c74156562adf8/charts/grafana-agent/templates/configmap.yaml) only the `log_level: info` value.

**Describe the solution you'd like**
Make value of `log_level` configurable using `values.yaml`.

**Comment by DandyDeveloper** [comment]
@MurzNN Oops. Thank you, I'll jump on that quickly.
