### ISSUE TITLE
[chart/redis-ha][REQUEST] Optionally enable HAProxy as sidecar containers

### ISSUE THREAD

**Issue by btwear** [DandyDeveloper/charts#179]
Kubernetes has pod number limit and it's very common that multiple Redis hosted in a cluster.

Redis Sentinel already reserve at least 3 pods to run.
Letting HAProxy optionally integrate with Redis as a sidecar can reduce additional resource spending(pods).

Also, reducing pods, deployments and services make cluster resources cleaner either.

**Comment by DandyDeveloper** [comment]
@btwear I think this came up elsewhere and I don't like this idea. HAProxy as a component is independent and as such, tying all the configuration into a single pod is going to be a huge mess but also prevent visibility of users consuming it. 

An extra 3-4 pods from HAProxy shouldn't really impact users that much.

I'm happy to hear the argument for this in more depth though. Can you explain?
