### ISSUE TITLE
[chart/redis-ha][BUG] Add apiVersion checks for PDB deprecations on install.

### ISSUE THREAD

**Issue by burnumd** [DandyDeveloper/charts#187]
**Describe the bug**
When installing/upgrading the redis-ha chart on a Kubernetes cluster running API v1.21+, a number of warnings are populated depending on the pod disruption budget configuration. They all read `policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget`.

**To Reproduce**
1. Set `.Values.podDisruptionBudget` to `minAvailable: 1`
2. Run `helm install dandydev/redis-ha`
3. See warning

**Expected behavior**
No warning is generated when installing/upgrading

**Additional context**
The release version of this resource has been available since K8s API v1.21. There is a change to [how the spec behaves](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) that needs to be addressed based on the default values.

**Comment by DandyDeveloper** [comment]
@burnumd This is expected, but yes, deprecations will need to be dealt with more gracefully. I'll do an ApiVersion check before applying the changes.
