### ISSUE TITLE
[chart/redis-ha][REQUEST] Migrate from Pod Security Policy to SecurityContext

### ISSUE THREAD

**Issue by pierluigilenoci** [DandyDeveloper/charts#204]
**Is your feature request related to a problem? Please describe.**

[Pod Security Policies](https://kubernetes.io/docs/concepts/security/pod-security-policy/) are deprecated and will be removed in Kubernetes v1.25.

Migration to another alternative is necessary.
To date there are some alternative solutions:
- [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/)
- [OPA Gatekeeper](https://github.com/open-policy-agent/gatekeeper)
- [Kyverno](https://github.com/kyverno/kyverno)
 
**Describe the solution you'd like**

A solution that is ecumenical and covers all the aforementioned alternatives is the use of [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) directly in the manifest of the chart.

This change must involve both ha-server and ha-proxy.

**Describe alternatives you've considered**

A possible solution would be to implement all the major alternatives within the chart but it is certainly a more onerous job.

**Additional context**

Related to #29

**Comment by joebowbeer** [comment]
kyverno-cli provides a convenient way to check the manifests statically.

The following command reports 7 failures vs the PSS [restricted profile](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) policies:

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply -r \
  <(helm template --repo https://dandydeveloper.github.io/charts redis-ha) \
  -
```

**Comment by pierluigilenoci** [comment]
@lord-kyron @DandyDeveloper can you please take a look?

**Comment by DandyDeveloper** [comment]
On it hopefully today or tomorrow. Sorry, this wasn't on my radar originally.

@joebowbeer @pierluigilenoci

**Comment by lord-kyron** [comment]
@DandyDeveloper are you going to look into this? Kubernetes 1.25 is close and if this is going to be deprecated, it will become a real problem.

**Comment by DandyDeveloper** [comment]
Yes, unfortunately just been busy and it's a holiday in Japan right now.

**Comment by pierluigilenoci** [comment]
@DandyDeveloper any news about this?

**Comment by DandyDeveloper** [comment]
@joebowbeer @pierluigilenoci I'm on this now, I will need to step away and deal with it in the morning. 

I'm currently using kyverno based on the pod-security policy. This all seems very sensible, I'm just working through and making sure the templating is accurate and working as intending.

**Comment by DandyDeveloper** [comment]
@joebowbeer @pierluigilenoci Please take a look at the PR, I need a couple pair of eyes to confirm this looks good.
