### ISSUE TITLE
[chart/redis-ha][BUG] - make ipv6 format bind optional - HAproxy deployment fails on kube that does not have ipv6 setup

### ISSUE THREAD

**Issue by ArcticSnowman** [DandyDeveloper/charts#216]
**Describe the bug**
Make ipv6 format bind optional - deployment fails on kube that does not have ipv6 setup

**To Reproduce**
Kube  v1.18.10 with only IPv4 setup

```
[ALERT] 214/163950 (1) : Starting proxy health_check_http_url: cannot create listening socket [:::8888]
[ALERT] 214/163950 (1) : Starting frontend ft_redis_master: cannot create listening socket [:::6379]
```

**Comment by DandyDeveloper** [comment]
@ArcticSnowman Checking and fixing this.

**Comment by DandyDeveloper** [comment]
@ArcticSnowman https://github.com/DandyDeveloper/charts/pull/223

Can you try running this and seeing if this resolves the issue? There may be IPv6 related bindings I have missed. This only impact HAProxy specifically.
