### ISSUE TITLE
[chart/grafana-agent>][override max_bytes_per_trace] 

### ISSUE THREAD

**Issue by camilo-alice** [DandyDeveloper/charts#231]
**Is your feature request related to a problem? Please describe.**
I would like to increase the max_bytes_per_trace override parameter.

**Describe the solution you'd like**
Add this configuration to the helm chart values.

**Describe alternatives you've considered**

**Additional context**
I don't know if this configuration is already available, I wasn't able to find.

**Comment by DandyDeveloper** [comment]
Closing as this is very out of date. I need to update a lot of stuff on the original chart :)
