### ISSUE TITLE
Allow setting annotations on Pods in StatefulSet

### ISSUE THREAD

**Issue by silvpol** [DandyDeveloper/charts#233]
Currently there is no way to set custom annotations on pods in the StatefulSet for Redis server, only on the StatefulSet itself. In our use case this prevents setting Cluster Autoscaler annotation causing scaling down to block. The annotation (`cluster-autoscaler.kubernetes.io/safe-to-evict: true`) is needed for recent K8s versions due to local storage being utitlised. I think there are more use cases for this as well. HAProxy deployment already offers this option so this functionality would complement it nicely.

**Comment by DandyDeveloper** [comment]
@silvpol Sorry for the delay: https://github.com/dandydeveloper/charts/blob/169cad792a9193844990ac6b355f7b27b607d6fb/charts/redis-ha/templates/redis-ha-statefulset.yaml#L32

`.Values.podAnnotations` exists? Isn't this what you're asking for?

**Comment by silvpol** [comment]
@DandyDeveloper thanks, I only looked in README, sorry about that. I found it in chart and it works as expected.
