### ISSUE TITLE
[chart/redis-ha][REQUEST] change default image tag for haproxy to alpine build image

### ISSUE THREAD

**Issue by martijnvdp** [DandyDeveloper/charts#248]
**Is your feature request related to a problem? Please describe.**
is there a reason to stick with the non alpine image for ha-proxy ? cant this also be the alpine release image like redis?

**Describe the solution you'd like**
change default image tag for haproxy to 2.6.9-alpine

**Additional context**
The alpine image seem to have less security issues

**Comment by DandyDeveloper** [comment]
@martijnvdp My only concern would be whether this has any negative impact on the scripts we use to provision things. 

Assuming it doesn't (I will check the PR and test) I have no concerns with this.
