### ISSUE TITLE
[chart/redis-ha][BUG] redhat w/ ulimit unlimited max out cpu & memory, could we add to helm chart a default maxconn?

### ISSUE THREAD

**Issue by lknite** [DandyDeveloper/charts#252]
**Describe the bug**
On some os's ulimit ends up being unlimited & haproxy will max out cpu & memory in this case.
Reference:  https://github.com/docker-library/haproxy/issues/194

**To Reproduce**
https://github.com/haproxy/haproxy/issues/2121

1. Deploy kubernetes on redhat 9
2. Deploy redis-ha helm chart

**Expected behavior**
haproxy to deploy normally

**Additional context**
Seems a good idea to specify a reasonable value in the haproxy helm chart:
![image](https://user-images.githubusercontent.com/92187614/231904471-a2178e7f-1174-405c-a340-e98917bfc523.png)

**Comment by lknite** [comment]
Since this seems to be a knows issue with the solution being to set maxconn, could we get this added to the helm chart as a value which can be set?  I'm actually using an argocd helm chart which uses this helm chart as a subchart, if maxconn were available to be set I could configure this to solve the issue.

**Comment by lknite** [comment]
I worked around this by adjusting ulimits at the container service level, in my case this is containerd fixed like this:
```
# sed -i 's/LimitNOFILE=infinity/LimitNOFILE=65535/' /usr/lib/systemd/system/containerd.service; systemctl daemon-reload
```

**Comment by wangycc** [comment]
I also encountered the same problem in the Linux 6.x kernel. Why is the same LimitNOFILE configuration working fine in lower versions?
