### ISSUE TITLE
[chart/redis-ha][REQUEST] 

### ISSUE THREAD

**Issue by amfleurke** [DandyDeveloper/charts#256]
**Is your feature request related to a problem? Please describe.**
I can't specify externalIPs for a (type: Loadbalancer) Service for HAProxy.

**Describe the solution you'd like**
have the field supported.
- in values: add haproxy.service.externalIPs.
- in redis-haproxy-service.yaml 
+  {{- if .Values.haproxy.service.externalIPs }}
+  externalIPs:
+    {{- range $key, $value := .Values.haproxy.service.externalIPs }}
+    - {{ $value }}
+    {{- end }}
+  {{- end }}
and documentation in README.md

**Describe alternatives you've considered**
none.

**Additional context**
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

**Comment by DandyDeveloper** [comment]
Merged PR. Closing.
