### ISSUE TITLE
Publish Action failing [BUG]

### ISSUE THREAD

**Issue by trawler** [DandyDeveloper/charts#261]
The publishing of updated charts is failing with the following error:

```
fatal: could not read Password for 'https://***@github.com': No such device or address
```

See: https://github.com/DandyDeveloper/charts/actions/runs/6274420303/job/17039782331#step:3:1

**Comment by trawler** [comment]
hi @DandyDeveloper - could you please take a look at this issue?
Thanks! 🙏

**Comment by venkatamutyala** [comment]
Hi @DandyDeveloper it looks like this chart is far ahead of what is published: https://artifacthub.io/packages/helm/dandydev-charts/redis-ha

**Comment by DandyDeveloper** [comment]
@trawler Fixed. I'm slowly going to get up to speed with everything and update what needs to be. 

I've neglected the repo for far too long - Sorry.
