### ISSUE TITLE
[chart/redis-ha][BUG] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by pdrastil** [DandyDeveloper/charts#268]
**Describe the bug**
I'm using redis-ha with 3 replicas together with Argo CD. After upgrading to redis-ha chart 4.23.0 -> 4.26.1 I'm seeing that Pods are getting stuck in Init:CrashLoopBackOff state. This is completely random and happens only on some clusters. Sometimes first replica starts correctly and second will get into this state. Reverting back to previous version always results in all replicas correctly starting. When poking into logs I've seen this message:

```
❯ kubectl logs argo-cd-redis-ha-server-1 -c config-init
Illegal instruction (core dumped)
 Start...
Illegal instruction (core dumped)
Illegal instruction (core dumped)
```

Any advice what might be wrong would be appreciated.

**To Reproduce**
No idea how to reproduce. Tested on 2 clusters with exactly same K8s version (1.26.2), contained and kernel. The first cluster started correctly all 3 replicas, on second cluster I'm getting CrashloopBackoff.

**Expected behavior**
All Redis replicas will start properly.

**Additional context**

**Comment by DandyDeveloper** [comment]
@pdrastil Nothing inbetween released on the config init bash script or the statefulset has changed that would impact this. 

You sure this isn't a node specific problem? You should probably check your kernel logs (`dmesg`) on the node that this seems to be happening on.

It could be the way our bash script is interacting with the host OS, but nothing between 4.23 -> 4.26.1 would have impacted this.

**Comment by pdrastil** [comment]
@DandyDeveloper I'm not 100% sure. As stated above - I have 2 exactly same EKS clusters on same Amazon Linux AMI image. In one of them redis-ha starts as expected, on second cluster it's in crashlooping state with error posted above. If I do the rollback to previous version with older Redis version both deployments starts fine. I'll try to take a look into `dmesg` to see if there is something else I can find.

**Comment by pdrastil** [comment]
@DandyDeveloper Hi thanks for a great tip - after checking kernel logs I've pinpointed issue to Dynatrace agent that killed `config-init` container.

**Comment by DandyDeveloper** [comment]
@pdrastil That's a relief! Thank you for coming back and letting me know.

I'll close the issue, feel free to reopen if it does come back again
