### ISSUE TITLE
[chart/<chart_name>][BUG] Helm Install Syntax Error

### ISSUE THREAD

**Issue by bshouse6** [DandyDeveloper/charts#270]
**Describe the bug**
When deploying this chart along with ArgoCD 2.9.3, when setting the redis-ha value to true, helm is throwing an error:

[error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context](rror: UPGRADE FAILED: YAML parse error on argo-cd/charts/redis-ha/templates/redis-haproxy-deployment.yaml: error converting YAML to JSON: yaml: line 53: mapping values are not allowed in this context)

**To Reproduce**
1. helm upgrade --install argocd . -n argocd --values value-sbx.yaml --dry-run

**Expected behavior**
The redis subchart deploys correctly.

**Additional context**
The latest community argocd chart deploys correctly without redis-ha and the subchart. 

version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.22.1"}

Running on MAC M1

**Comment by DandyDeveloper** [comment]
@bshouse6 Whats the contents of `value-sbx.yaml `?

**Comment by DandyDeveloper** [comment]
@bshouse6 There's a bunch of errors in that values file. 

`affinity:` has a pipe that causes interpretation of everything else as a string
![image](https://github.com/DandyDeveloper/charts/assets/18436531/ad04408b-09e5-4bea-bb33-5404f84dbfe4)

New line string is causing bad YAML interpretation: 
![image](https://github.com/DandyDeveloper/charts/assets/18436531/3f7ad287-c6ad-43d4-85b9-eb0cf5967a4a)

There's also a lot of dupes. 

Is this directly from the ArgoCD Repo? They need to fix this file! Got a link to the repo?

**Comment by DandyDeveloper** [comment]
Also I'm a bit confused, they are using the redis-ha as a direct dependency, there's no value overrides in the default ArgoCD Helm chart: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml

You sure you didn't prepare the values yourself? Got a link for me? 
@bshouse6

**Comment by bshouse6** [comment]
https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L1458

That section I pulled is from that values file, the only things we modified were the image/repo, tag, and enabled. So this might be an issue in the argocd chart vs. the redis/dependency, given I used the default values.

**Comment by DandyDeveloper** [comment]
@bshouse6 

I think you did a bad copy-paste, it looks OK in their original.

![image](https://github.com/DandyDeveloper/charts/assets/18436531/d4809598-59e3-4342-ad79-c32b88be76db)

**Comment by bshouse6** [comment]
I am going to close this out. Looks like there is something up with the values files/templating not working, not ness. something with this chart. For me, out of the box, the redis-ha flags do not work but that might be values needed or not needed that are hosing things up.

I changed that pipe for the affinity values, and that resolved the error. We ended up going with another image/path.
