### ISSUE TITLE
[chart/redis-ha][BUG]

### ISSUE THREAD

**Issue by stil4m** [DandyDeveloper/charts#28]
**Describe the bug**
Default value `haproxy.enabled` to `false` breaks `service-test. 
The service test specifies a hard coded reference to the `haproxy` service. While HAProxy is not enabled, the test pod will fail, and this in its place will fail deployments (i.e. CI) that require all test pods to succeed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy the chart with HAPoxy disabled.
2. Test pod will fail (https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/tests/test-redis-ha-pod.yaml).

**Expected behaviour**
No test pods will fail when HAProxy is disabled.

**Additional context**
For my setup I believe I do not necessarily need the HAProxy. The 3rd-party software I use relies on configuring the sentinel endpoints (I use the created services for this). I'm not sure why I should enable/require the HAProxy. My knowledge of HAProxy is too low to understand it in the setup of the chart. Could you explain this?

**Comment by DandyDeveloper** [comment]
@stil4m Good catch, thank you. Quick fix, I'll see if I can do that tomorrow.

**Comment by stil4m** [comment]
No hurries. I can patch it as well. Let me know.

Would a simple if suffice on the service test? Or would you like to configure the test in a different way? For example, connect to a sentinel?

**Comment by DandyDeveloper** [comment]
@stil4m Thank you for jumping on this, been a little overwhelmed with both work and life. Appreciate the contribution, left a quick comment to get this fixed.
