### ISSUE TITLE
redis-ha psp

### ISSUE THREAD

**Issue by ivomarino** [DandyDeveloper/charts#29]
short question regarding podSecurityPolicy (PSP), will it be supported by this chart? Actually getting
```
4m47s       Warning   FailedCreate            statefulset/redis-cache-redis-ha-server                    create Pod redis-cache-redis-ha-server-0 in StatefulSet redis-cache-redis-ha-server failed error: pods "redis-cache-redis-ha-server-0" is forbidden: unable to validate against any pod security policy: []
```
on a node where psp is enabled. Thanks for infos.

**Comment by DandyDeveloper** [comment]
@ivomarino Yes, it wouldn't be too hard to implement support for this. Especially if it's unable to be deployed to clusters set to force validate. 

I'll add it to the to do.

**Comment by ivomarino** [comment]
Thanks @DandyDeveloper, really appreciated;)
