### ISSUE TITLE
[chart/redis-ha][REQUEST] Redis 6.0 TLS support

### ISSUE THREAD

**Issue by SarjakShirishShah** [DandyDeveloper/charts#30]
**Is your feature request related to a problem? Please describe.**
Now that Redis 6.0 supports TLS, would it be possible to have support in the chart for configuring TLS?

**Describe the solution you'd like**
Generally I would use the redis.config or redis.customconfig directive to configure tls related configurations, but I also need to be able to pass in additional secrets for the TLS certs.

**Describe alternatives you've considered**
None

**Comment by tbnguyen1407** [comment]
Hello any update on this?

**Comment by DandyDeveloper** [comment]
@tbnguyen1407 I was hoping @SarjakShirishShah would be able to fix the recent conflicts. I may have to take over though. Please bare with me.

**Comment by SarjakSShah** [comment]
> @tbnguyen1407 I was hoping @SarjakShirishShah would be able to fix the recent conflicts.
> 
> Waiting on that. Looks like he's mentioned it recently, so I'll hold off touching it until next week if nothing gets done.

@DandyDeveloper : As I mentioned on the PR sometime earlier today, I will redo the TLS stuff sometime this week, thanks

**Comment by DandyDeveloper** [comment]
@SarjakShirishShah Thank you!
