### ISSUE TITLE
[chart/redis-ha][BUG] - incorrect master IP being returned by sentinel on startup 

### ISSUE THREAD

**Issue by thameezb** [DandyDeveloper/charts#33]
**Describe the bug**
Incorrect master IP is returned by sentinel iff current master-pod is killed, and the new pod starts up before the sentinels can elect a new master. This leads to a timeout when attempting to connect to the cluster, and finally results in a forced failover.

**To Reproduce**
1. Kill current master pod 
2. Exec onto new pending pod -> `config-init` container 
3. Run `redis-cli -h app-redis-redis-ha -p 26379 sentinel get-master-addr-by-name mymaster | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'`
4. The ip returned will be of the old master pod (attempting to run `redis-cli -h "$MASTER" ping` will timeout as expected)

**Expected behavior**
On pod startup, above command should return IP of newly elected master, leading to a correct addition to the cluster (without the forced failover needing to occur -> as this throws errors on most clients)

**Additional context**
Perhaps add a pause [here](https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/_configs.tpl#L91) to ensure that the correct IP is returned?

**Comment by DandyDeveloper** [comment]
@thameezb This may be something I am limited in fixing without a fair bit of time. Sorry for the delay in responding, I'll try and jump on this when I can.

**Comment by devsinghnaini** [comment]
@DandyDeveloper  Any news on this issue. We are also facing issue in client side application.

**Comment by DandyDeveloper** [comment]
@devsinghnaini @thameezb I am about to merge https://github.com/DandyDeveloper/charts/pull/23 which should give better results in initialization of these pods and has a much better chance at finding the right master. 

Although I haven't personally experienced your issues, can you try testing this

**Comment by DandyDeveloper** [comment]
I'm going to close this as we haven't had any feedback. Feel free to reopen.
