### ISSUE TITLE
[chart/redis-ha][BUG] redis-ha-statefulset writes invalid labels

### ISSUE THREAD

**Issue by leonsp-ai** [DandyDeveloper/charts#39]
**Describe the bug**
`redis-ha-statefulset` breaks string labels that look like booleans. The cause is that it writes labels without quotes: https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/redis-ha-statefulset.yaml#L35

**To Reproduce**
1. Set a string label:
    ```
    redis-ha:
      labels:
        dns: "true"
    ```
2. Try to deploy `redis-ha`
3. `redis-ha` transforms that to a boolean label:
    ```
    labels:
      app: redis-ha
      dns: true
    ```
4. Deployment fails with an error similar to:
    ```
    kapp: Error: Applying update statefulset/foo-redis-ha-server (apps/v1) namespace: foo:
      Updating resource statefulset/foo-redis-ha-server (apps/v1) namespace: foo:
        StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec:     v1.StatefulSetSpec.Template: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Labels:
          ReadString: expects " or n, but found t, error found in #10 byte of ...|y","dns":true,"kapp.|..., bigger context ...|":"redis-ha","dns":true,"kapp.k14s.io/association":"v1.43bdfa7e6010c97|... (reason: BadRequest)
   ```

**Expected behavior**

Quote the labels when writing them so that strings can't turn into booleans.

**Comment by DandyDeveloper** [comment]
That's odd. Sorry I missed this issue, will fix

**Comment by DandyDeveloper** [comment]
@leonsp-ai #40 PR should fix this BUT I actually think this is the known bug in helm [here](https://github.com/helm/helm/issues/1707) wherein the intepretation is boolean (in true/false) and has the same issue with floats. 

Even with a `| toString` it can't be solved without some ridiculous workaround, ideally you should wrap your items in quotes OR use the flag `--set-string` in the helm command.

**Comment by leonsp-ai** [comment]
Thank you!
