### ISSUE TITLE
[chart/redis-ha][REQUEST] Custom labels for all pods

### ISSUE THREAD

**Issue by leonsp-ai** [DandyDeveloper/charts#40]
**Is your feature request related to a problem? Please describe.**
My team assigns network policies and associates pod ownership with our team using labels. `redis-ha` offers custom labels for some pods but not all. For example, `redis-ha-statefulset` pods support custom labels.

These do not:

- `redis-haproxy-deployment`
- `test-redis-ha-configmap`
- `test-redis-ha-pod`

**Describe the solution you'd like**
The chart should apply the same custom labels to all pods including:

- `redis-haproxy-deployment`
- `test-redis-ha-configmap`
- `test-redis-ha-pod`

**Describe alternatives you've considered**
Manually editing pods or deployments after creation is a bad idea.

Standard labels allow for network policy flexibility but not for associating team ownership on a multi-team cluster.

**Comment by DandyDeveloper** [comment]
@leonsp-ai haproxy was my oversight, sorry. The test ones is a relatively easy fix. Thanks for bringing this to my attention

**Comment by DandyDeveloper** [comment]
@leonsp-ai Please see referenced issue, sorry this has taken so long, lots of personal and work commitments have lead to neglect!

**Comment by leonsp-ai** [comment]
Thanks Aaron!
