### ISSUE TITLE
[chart/redis-ha][INFO] - Password protection for Sentinel

### ISSUE THREAD

**Issue by phlegx** [DandyDeveloper/charts#43]
Hi there!

I'm trying to add password protection to my sentinels and I found out that these two things must be set to make it work in `sentinel.conf`:

```
requirepass <password>
sentinel auth-pass <master-group-name> <password>
```

What I have seen, `requirepass` cannot be set via `sentinel.config`.

How can I set these correctly with `redis-ha` chart to make sentinel auth possible?

thanks in advance!

**Comment by DandyDeveloper** [comment]
@phlegx Thank you for the PR and issue, I've made a comment that references another PR that MAY already achieve the sentinel security. Let me know.
