### ISSUE TITLE
[chart/redis-ha][BUG] PodDisruptionBudget applies to test pods

### ISSUE THREAD

**Issue by leonsp-ai** [DandyDeveloper/charts#45]
**Describe the bug**
The [PodDisruptionBudget selector](https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/redis-ha-pdb.yaml#L10) matches the labels not only on the [StatefulSet](https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/redis-ha-statefulset.yaml#L6) but also on the two test containers:

- <https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/tests/test-redis-ha-configmap.yaml#L6>
- <https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/templates/tests/test-redis-ha-pod.yaml#L6>

**To Reproduce**
1. Deploy redis-ha with these values:

```yaml
redis-ha:
  haproxy:
    enabled: true
  labels:
    dns: "true"
  metrics:
    enabled: true
  podDisruptionBudget:
    # maxUnavailable: 1
    minAvailable: 2
  replicas: 3
```

2. Check the pod labels:

```
$ kubectl get pods --show-labels | grep redis-ha
samproxy-redis-ha-configmap-test             0/1     Completed   0          1h    app=redis-ha,foo/app=samproxy,release=samproxy
samproxy-redis-ha-server-0                   2/2     Running     0          1h    app=redis-ha,foo/app=samproxy,release=samproxy,samproxy-redis-ha=replica
samproxy-redis-ha-server-1                   2/2     Running     0          1h    app=redis-ha,foo/app=samproxy,release=samproxy,samproxy-redis-ha=replica
samproxy-redis-ha-server-2                   2/2     Running     0          12d   app=redis-ha,foo/app=samproxy,release=samproxy,samproxy-redis-ha=replica
samproxy-redis-ha-service-test               0/1     Completed   0          1h    app=redis-ha,foo/app=samproxy,release=samproxy
```

3. Check the PodDisruptionBudget:

```sh
$ kubectl describe pdb samproxy-redis-ha-pdb                                   
Name:           samproxy-redis-ha-pdb
Namespace:      opentelemetry
Min available:  2
Selector:       app=redis-ha,foo/app=samproxy,release=samproxy
Status:
    Allowed disruptions:  1
    Current:              3
    Desired:              2
    Total:                5
Events:                   <none>
```

**Expected behavior**
The total pods for the budget should be 3, not 5.

**Additional context**
We use `kapp` to deploy `helm` templates. I have a possibly related feature request for custom labels: #40

**Comment by DandyDeveloper** [comment]
@leonsp-ai Thank you for the PR. Just waiting for chart bump!
