### ISSUE TITLE
[chart/redis-ha] Support for livenessProbe options.

### ISSUE THREAD

**Issue by luishdez** [DandyDeveloper/charts#50]
**Is your feature request related to a problem? Please describe.**
Currently we have a problem whehere livenessProbe for HaProxy has a 1s timeout, k8s it's killing it and causing lots connections "Redis server went away" when our network it's on peaks.

**Describe the solution you'd like**
Add support for live livenessProbe values

If ok I can create the PR

**Comment by DandyDeveloper** [comment]
Fixed.
