### ISSUE TITLE
[chart/redis-ha][BUG]

### ISSUE THREAD

**Issue by ibmboy19** [DandyDeveloper/charts#54]
**Describe the bug**
Config-init File: templates/_configs.tpl

if user setting custom Values.redis.port, 
Line 93 missing '-p {{ .Values.redis.port }}' always cause the ping command to timeout!
```
find_master() {
        echo "Attempting to find master"
        if [ "$(redis-cli -h "$MASTER"{{ if .Values.auth }} -a "$AUTH"{{ end }} ping)" != "PONG" ]; then
```

**Comment by DandyDeveloper** [comment]
@ibmboy19 I have tried this with some recent updates. Looks OK:

values.yml
```yaml
redis:
  port: 6879
```
It all seems to work. 

![image](https://user-images.githubusercontent.com/18436531/92320284-565f5580-f05b-11ea-94a5-b0a479be54df.png)
