### ISSUE TITLE
[charts/redis-ha][BUG] redis-ha service connects to read-only replicas

### ISSUE THREAD

**Issue by jeffwalsh** [DandyDeveloper/charts#57]
**Describe the bug**

**To Reproduce**
1.
```
    helm upgrade --install redis-ha dandydeveloper/redis-ha \
      --set auth=true,redisPassword=password \
      --namespace monitoring \
      --version "4.6.2"
```

2.
Add `redis-ha.monitoring.svc.cluster.local` as your Redis HOST in your app, as the instructions indicate:
```
Redis can be accessed via port 6379 and Sentinel can be accessed via port 26379 on the following DNS name from within your cluster:
redis-ha.monitoring.svc.cluster.local
```

3.
Try to use Redis.

4.
Mostly get this error as it round robins between master and slaves:
`READONLY You can't write against a read only replica.`

**Expected behavior**
I only connect to the master.

**Additional context**
What am I doing wrong?

**Comment by Tijmen34** [comment]
Ran into this issue as well deploying version 4.9.1. Deploying an older version (4.8.3 in my case) had no issues..

**Comment by DandyDeveloper** [comment]
@jeffwalsh Interesting, I recently added ro_replica support but it should only reference them when `ro_replicas` is populated in the chart. Let me investigate. Sorry.

**Comment by DandyDeveloper** [comment]
@jeffwalsh @Tijmen34 Wait, are we sure this is right? 

We're using sentinel with HA, so the way you should be connecting and writing to your environment is through Sentinel, not Redis. The Redis headless service is likely to just select a random endpoint to route this if you use the `redis-redis-ha` service for writing.

If you enable to haproxy, then that will give you the outcome I think you're expecting as it kind of replicates the behavior you'd expect to see by confirming the logical master.

**Comment by DandyDeveloper** [comment]
As an example, with haproxy enabled: 

```
haproxy;
  enabled: true
```

Then you'll get what I think you're expecting here.
```
root@redis-cli:/data# redis-cli -h redis-redis-ha-haproxy
redis-redis-ha-haproxy:6379> SET xyz 123
OK
redis-redis-ha-haproxy:6379> 
```

**Comment by Tijmen34** [comment]
I am not really familiar that much with Redis, but within the values.yaml, HA Proxy is recommended when externally exposing Redis clusters. For my case, I simply want it to be internally reachable by another service. Using the same internal URL as @jeffwalsh did, expectation is that it should select a replica that is read/writable. For some reason v4.8.3 works perfectly as we expected it to be, but v4.9.1 does not. I will try it out with HA Proxy enabled, but shouldn't it be **always** recommended then?

```
## Enables a HA Proxy for better LoadBalancing / Sentinel Master support. Automatically proxies to Redis master.
## Recommend for externally exposed Redis clusters.
```

**Comment by DandyDeveloper** [comment]
@Tijmen34 Since this is Redis HA, you should connect through Sentinel to determine the master and make subsequent connections to Redis, pretty much all libraries have sentinel support, see:

https://redis.io/topics/sentinel

https://redis.io/topics/sentinel-clients

Here's a Python example: https://stackoverflow.com/questions/45885881/how-to-create-redis-python-client-from-sentinel-url

If this did work before, it's possible that in itself was a bug / luck that your headless service was directed at the master.

**Comment by Tijmen34** [comment]
Enabling HA Proxy and connecting to that fixed the issue for me at least, I hope it also fixes it for @jeffwalsh

**Comment by DandyDeveloper** [comment]
Closing as I haven't heard an update

**Comment by jeffwalsh** [comment]
@DandyDeveloper  So I just change the URL to I connect to, to `redis-ha-haproxy.namespace.svc.cluster.local` to hit the haproxy? I get "EOF" when my redis client in my Go app attempts to connect to this instead. I do see the `redis-ha-haproxy` service though in `kubectl get services`, and bumped my version to 4.9.1 like @Tijmen34 did.

**Comment by endianjoakim** [comment]
I'm having the same issue as @jeffwalsh. Conneting to `redis-ha-haproxy:6379`. Basically using default values, just enabling HA Proxy. 

```yaml
haproxy:
  enabled: true
```

If I have 3 `redis-ha-server` replicas, every 3rd call is OK, the rest `EOF`. If I have 2 `redis-ha-server` replicas, every other call is `EOF`. 

This does not seem to change if I have 1,2, or 3 HA Proxy replicas running. Tried w/ both `4.8.3` and `4.9.3` versions of `redis-ha`. Same issue. 

Configuration issue or something else?

**Comment by DandyDeveloper** [comment]
@endianjoakim You sure you're connecting to the HA Proxy instance? Ifyou are, sounds like something is failing over to the secondary all the time.

HA Proxy should only ever have 1 instance to LB over (Primary). Check your logs for HA Proxy, and the Redis instances. Should be something bouncing everything around.

**Comment by endianjoakim** [comment]
Thanks for a prompt reply. I swapped my code to use the sentinel solution instead. That was stable over night, so I'll keep it.
