### ISSUE TITLE
[chart/<redisha>][REQUEST] 

### ISSUE THREAD

**Issue by sabareeshkkanan** [DandyDeveloper/charts#61]
**Is your feature request related to a problem? Please describe.**
How to configure redis ha to work cross region. Lets say i have separate Kubernetes cluster on region A and B

**Comment by DandyDeveloper** [comment]
@sabareeshkkanan Can you explain your use case a little more? 

You want 1 Redis cluster, but the primary / secondary spread over 2 clusters? 

So it is possible, but needs a fair bit of config changes. Nothing specific exists in the chart for this, but it does support this.

**Comment by DandyDeveloper** [comment]
@sabareeshkkanan Any news? Closing for now. Feel free to reopen

**Comment by skas-zilo** [comment]
> [@sabareeshkkanan](https://github.com/sabareeshkkanan) Can you explain your use case a little more?
> 
> You want 1 Redis cluster, but the primary / secondary spread over 2 clusters?
> 
> So it is possible, but needs a fair bit of config changes. Nothing specific exists in the chart for this, but it does support this.

What need to be config for support this?
