### ISSUE TITLE
[chart/redis-ha][REQUEST] allow setting terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by bootc** [DandyDeveloper/charts#62]
**Is your feature request related to a problem? Please describe.**
In order to help with graceful shutdown of Redis and its components, please allow setting the Pod's `terminationGracePeriodSeconds` parameter.

**Additional context**
We can already set the container lifecycle settings but the termination grace period is not changeable from the default 30 seconds. It would be useful to be able to set this on large Redis instances to allow the full RDB contents to be written to disk. See https://learnk8s.io/graceful-shutdown.

**Comment by paranoidsp** [comment]
Looks like this is already possible via https://github.com/DandyDeveloper/charts/blob/fde04e7ab7dd48c46b31cee8ea4fc42dd3bce6ef/charts/redis-ha/values.yaml#L207

**Comment by bootc** [comment]
Indeed, it looks like it is now. Closing this off.
