### ISSUE TITLE
[chart/redis-ha][REQUEST] Pull S3 credentials from k8s secret

### ISSUE THREAD

**Issue by j771** [DandyDeveloper/charts#65]
**Is your feature request related to a problem? Please describe.**
AWS S3 credentials should be able to be pulled from a Kubernetes secret instead of a string in the values.yaml file.

**Describe the solution you'd like**
Reference a Kubernetes secret containing S3 keys.

**Describe alternatives you've considered**

**Additional context**

**Comment by DandyDeveloper** [comment]
@j771 Simple enough to implement, I'll see if we can get this done.

**Comment by j771** [comment]
@DandyDeveloper Do you have a time estimate on getting this done? If not soon I can see about just doing it on my own.

**Comment by j771** [comment]
https://github.com/DandyDeveloper/charts/pull/66
