### ISSUE TITLE
Does HAProxy support TLS?

### ISSUE THREAD

**Issue by drmy** [DandyDeveloper/charts#67]
Hi,

In my case, I've enabled the built-in HAProxy and NodePort so that my external client can access to the Redis through the HAProxy.
I also need a secure connection between my client (outside the Kubernetes) and the Redis HAProxy.

Does it support this feature?

Thanks,
Hujun

**Comment by DandyDeveloper** [comment]
@drmy Originally, the plan was to rely on Ingress in-front of the LB to manage that. 

Right now, I don't think we support it, but we definitely could. Would not be a bad idea at all for those using NodePort / LB that doesn't have ingress on top of them.

**Comment by drmy** [comment]
> @drmy Originally, the plan was to rely on Ingress in-front of the LB to manage that.
> 
> Right now, I don't think we support it, but we definitely could. Would not be a bad idea at all for those using NodePort / LB that doesn't have ingress on top of them.

It would be great to have this feature. Please let us know when the feature is ready to use.
Thank you very much!

**Comment by RoyKimYYZ** [comment]
should HA-proxy also support port 26379 for sentinel connection?

**Comment by DandyDeveloper** [comment]
@RoyKimYYZ I think I answered this question in your original issue posted about Sentinel in HAProxy. 

All good? 

Aside from that, TLS support is still on the cards, I just don't have much time to commit to larger changes right this moment. Family life!

**Comment by RoyKimYYZ** [comment]
All Good thank you.
