### ISSUE TITLE
[chart/redis-ha][BUG]

### ISSUE THREAD

**Issue by akevdmeer** [DandyDeveloper/charts#76]
**Describe the bug**
The redis-server process (pid 1) does not expect to reap the processes spawned for the exec probes. Defunct `timeout` processes accumulate and when redis-server reaps such a process it logs this warning: `wait3() returned a pid (4861) we can't find in our scripts execution queue!`

**To Reproduce**
Check the process list and the logs for redis-server containers.

**Expected behavior**
There should be no accumulation of defunct processes, and no warnings logged for reaping the processes spawned for the probes.

**Comment by nunoguerreirorosa** [comment]
I am also seeing the container logs to be triggering this error every x seconds. What is the impact ?

"wait3() returned a pid (xxxx) we can't find in our scripts execution queue!"

**Comment by DandyDeveloper** [comment]
@nunoguerreirorosa @akevdmeer I have never seen this error before. I've got about 15 of these clusters running in production and looking at my logs, can't ever see that error being raised. 

Do you use some kind of lua scripts as an extension to Redis? 

Can you tell me more about your environment / deployment values?

**Comment by DandyDeveloper** [comment]
I have actually just realised I haven't upgraded these in a while :) Going to test with my latest deployment.

**Comment by DandyDeveloper** [comment]
I see the problem with processes not being reaped. Let me see if I can figure out how to fix it. I'm guessing its a result of either the large TLS updates, or Redis version update.

**Comment by DandyDeveloper** [comment]
I'm not entirely sure on the interaction with `timeout -s` and Docker containers, but it does appear to just indefinitely keep these processes running. 

It was introduced via the TLS PR. 

I think it's better to just remove the timeout and have submitted PR #77 for now. 

Merging shortly. This should be fixed in 4.10.4.
