### ISSUE TITLE
[chart/redis-ha][BUG]

### ISSUE THREAD

**Issue by nunoguerreirorosa** [DandyDeveloper/charts#78]
**Describe the bug**
I am deploying v4.10.4 of the redis-ha chart in staging kubernetes cluster (Azure) with 2 replicas and one of the replicas is not able to access the master node through the redis-ha-haproxy. 

PS: I have it running in production with no issues with 3 replicas.

**To Reproduce**
Settings below apply both for HAProxy and Redis:
- replicas: 2
- hardAntiAffinity: true
- Quorum: 1

**Expected behavior**
redis-ha-haproxy is accessible from either node.

**Additional context**
PODS:
redis-ha-haproxy-fbb7b4cfd-tps4m   1/1     Running   0          19m   10.244.42.87   vmss000001   <none>           <none>
redis-ha-haproxy-fbb7b4cfd-wkrb2   1/1     Running   0          19m   10.244.42.11   vmss000000   <none>           <none>
redis-ha-server-0                  2/2     Running   0          19m   10.244.42.56   vmss000001   <none>           <none>
redis-ha-server-1                  2/2     Running   0          18m   10.244.42.42   vmss000000   <none>           <none>

SERVICES:
redis-ha              ClusterIP   None           <none>        6379/TCP,26379/TCP   25m
redis-ha-announce-0   ClusterIP   10.0.29.229    <none>        6379/TCP,26379/TCP   25m
redis-ha-announce-1   ClusterIP   10.0.87.103    <none>        6379/TCP,26379/TCP   25m
redis-ha-haproxy      ClusterIP   10.0.240.163   <none>        6379/TCP             25m

redis-ha-server-0 (node1) --- Everything okay in this container. Can also access the master node through redis-ha-haproxy:6379
redis-ha-server-1 (node2) -- Problematic 

logs on redis-ha-server-1  redis container
1:S 19 Nov 2020 12:53:01.198 * Connecting to MASTER 10.0.29.229:6379
1:S 19 Nov 2020 12:53:01.198 * MASTER <-> REPLICA sync started
1:S 19 Nov 2020 12:54:02.376 # Timeout connecting to the MASTER...

logs on redis-ha-server-1 sentinel container
1:X 19 Nov 2020 12:50:52.030 # Sentinel ID is bc16ddc9a19ce8f3ff5ec8f31a2d6b94436af8a3
1:X 19 Nov 2020 12:50:52.030 # +monitor master mymaster 10.0.29.229 6379 quorum 2
1:X 19 Nov 2020 12:51:02.038 # +sdown master mymaster 10.0.29.229 6379

logs on redis-ha-haproxy for node2
[NOTICE] 323/124217 (1) : New worker #1 (6) forked
[WARNING] 323/124219 (6) : Server check_if_redis_is_master_0/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1000ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 323/124219 (6) : Server check_if_redis_is_master_0/R1 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT] 323/124219 (6) : backend 'check_if_redis_is_master_0' has no server available!
[WARNING] 323/124219 (6) : Server check_if_redis_is_master_1/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1001ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 323/124219 (6) : Server check_if_redis_is_master_1/R1 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1000ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT] 323/124219 (6) : backend 'check_if_redis_is_master_1' has no server available!
[WARNING] 323/124219 (6) : Server bk_redis_master/R0 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1000ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 323/124219 (6) : Server bk_redis_master/R1 is DOWN, reason: Layer4 timeout, info: " at step 1 of tcp-check (connect)", check duration: 1001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT] 323/124219 (6) : backend 'bk_redis_master' has no server available!

**Comment by DandyDeveloper** [comment]
@nunoguerreirorosa 

```
1:S 19 Nov 2020 12:53:01.198 * Connecting to MASTER 10.0.29.229:6379
```
What is the state of this IP address? If you exec into that pod and try to `redis-cli` and set a key. Does it work?

Do you have logs from the master?

**Comment by nunoguerreirorosa** [comment]
That IP refers to the service "redis-ha-announce-0" ClusterIP 10.0.29.229 which is pointing to redis-server-0 pod (master).
I did an exec on the redis-server-0 and access "redis-cli -h redis-ha-haproxy" and did set a key successfully.

Logs on master are the usual.

Redis is ready to accept connections.
Sentinel is monitoring master.

**Comment by nunoguerreirorosa** [comment]
I notice as well long initializations when I reinstall the chart for the slave node which has the problem. When I check the logs of the config-init I can find messages like the following "Could not connect to Redis at 10.0.51.50:6379: Operation timed out" That IP refers to the redis-ha-announce-0 service which is pointing to the master node, which is the pod redis-ha-server-0 which is working fine.

PS: This is a different installation with different IPs from the one reported but that has the same issue.

config-init log of redis-ha-server-1

Thu Nov 19 13:47:53 UTC 2020 Start...
Initializing config..
Copying default redis config..
  to '/data/conf/redis.conf'
Copying default sentinel config..
  to '/data/conf/sentinel.conf'
Identifying redis master (get-master-addr-by-name)..
  using sentinel (redis-ha), sentinel group name (mymaster)
  Thu Nov 19 13:47:53 UTC 2020..
  Thu Nov 19 13:47:53 UTC 2020 Found redis master (10.0.51.50)
Identify announce ip for this pod..
  using (redis-ha-announce-1) or (redis-ha-server-1)
  identified announce (10.0.24.31)
Verifying redis master..
  ping (10.0.51.50:6379)
  Thu Nov 19 13:47:53 UTC 2020..
Could not connect to Redis at 10.0.51.50:6379: Operation timed out
Could not connect to Redis at 10.0.51.50:6379: Operation timed out
Could not connect to Redis at 10.0.51.50:6379: Operation timed out
  Thu Nov 19 13:54:39 UTC 2020 Can't ping redis master (10.0.51.50)
Attempting to force failover (sentinel failover)..
  on sentinel (redis-ha:26379), sentinel grp (mymaster)
  Thu Nov 19 13:54:39 UTC 2020..
  Thu Nov 19 13:54:39 UTC 2020 Failover returned with 'NOGOODSLAVE'
Setting defaults for this pod..
Setting up defaults..
  using statefulset index (1)
Getting redis master ip..
  blindly assuming (redis-ha-announce-0) or (redis-ha-server-0) are master
  identified redis (may be redis master) ip (10.0.51.50)
Setting default slave config for redis and sentinel..
  using master ip (10.0.51.50)
Updating redis config..
  we are slave of redis master (10.0.51.50:6379)
Updating sentinel config..
  evaluating sentinel id (${SENTINEL_ID_1})
  sentinel id (bc16ddc9a19ce8f3ff5ec8f31a2d6b94436af8a3), sentinel grp (mymaster), quorum (1)
  redis master (10.0.51.50:6379)
  announce (10.0.24.31:26379)
Thu Nov 19 13:54:39 UTC 2020 Ready...

**Comment by nunoguerreirorosa** [comment]
From Inside redis-ha-server-0 I can do redis-cli through redis-ha-announce-0 or redis-ha-haproxy and can set keys however it says there are no connected slaves.

role:master
connected_slaves:0

**Comment by DandyDeveloper** [comment]
@nunoguerreirorosa What happens when you do the same thing to the master from one of the broken slaves?

**Comment by nunoguerreirorosa** [comment]
Values.yaml

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
image:
  repository: redis
  tag: 6.0.7-alpine
  pullPolicy: IfNotPresent

## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
## This imagePullSecrets is only for redis images
##
imagePullSecrets: []
# - name: "image-pull-secret"

## replicas number for each component
replicas: 2

## read-only replicas
## indexed slaves get never promoted to be master
## index starts with 0 - which is master on init
## i.e. "8,9" means 8th and 9th slave will be replica with replica-priority=0
## see also: https://redis.io/topics/sentinel
ro_replicas: ""

## Kubernetes priorityClass name for the redis-ha-server pod
# priorityClassName: ""

## Custom labels for the redis pod
labels: {}

configmap:
  ## Custom labels for the redis configmap
  labels: {}

## Pods Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  ## Specifies whether a ServiceAccount should be created
  ##
  create: true
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the redis-ha.fullname template
  # name:
  ## opt in/out of automounting API credentials into container
  ## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  automountToken: false

## Enables a HA Proxy for better LoadBalancing / Sentinel Master support. Automatically proxies to Redis master.
## Recommend for externally exposed Redis clusters.
## ref: https://cbonte.github.io/haproxy-dconv/1.9/intro.html
haproxy:
  enabled: true
  # Enable if you want a dedicated port in haproxy for redis-slaves
  readOnly:
    enabled: false
    port: 6380
  replicas: 2
  image:
    repository: haproxy
    tag: 2.0.4
    pullPolicy: IfNotPresent

  ## Custom labels for the haproxy pod
  labels: {}

  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

  annotations: {}
  resources: {}
  emptyDir: {}

  ## PodSecurityPolicy configuration
  ## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  ##
  podSecurityPolicy:
    ## Specifies whether a PodSecurityPolicy should be created
    ##
    create: false

  ## Enable sticky sessions to Redis nodes via HAProxy
  ## Very useful for long-living connections as in case of Sentry for example
  stickyBalancing: false
  ## Kubernetes priorityClass name for the haproxy pod
  # priorityClassName: ""
  ## Service type for HAProxy
  ##
  service:
    type: ClusterIP
    loadBalancerIP:
    annotations: {}
  serviceAccount:
    create: true
  ## Official HAProxy embedded prometheus metrics settings.
  ## Ref: https://github.com/haproxy/haproxy/tree/master/contrib/prometheus-exporter
  ##
  metrics:
    enabled: false
    # prometheus port & scrape path
    port: 9101
    portName: http-exporter-port
    scrapePath: /metrics

    serviceMonitor:
      # When set true then use a ServiceMonitor to configure scraping
      enabled: false
      # Set the namespace the ServiceMonitor should be deployed
      #namespace: extense-monitoring
      # Set how frequently Prometheus should scrape
      #interval: 30s
      # Set path to redis-exporter telemtery-path
      #telemetryPath: /metrics
      # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
      labels: {}
      # Set timeout for scrape
      # timeout: 10s
  init:
    resources: {}
  timeout:
    connect: 4s
    server: 120s
    client: 120s
    check: 2s
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
    runAsNonRoot: true

  ## Whether the haproxy pods should be forced to run on separate nodes.
  hardAntiAffinity: true

  ## Additional affinities to add to the haproxy pods.
  additionalAffinities: {}

  ## Override all other affinity settings for the haproxy pods with a string.
  affinity: |

  ## Custom config-haproxy.cfg files used to override default settings. If this file is
  ## specified then the config-haproxy.cfg above will be ignored.
  # customConfig: |-
    # Define configuration here
  ## Place any additional configuration section to add to the default config-haproxy.cfg
  # extraConfig: |-
    # Define configuration here

  ## Container lifecycle hooks
  ## Ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  lifecycle: {}

## PodSecurityPolicy configuration
## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
##
podSecurityPolicy:
  ## Specifies whether a PodSecurityPolicy should be created
  ##
  create: false

## Role Based Access
## Ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
rbac:
  create: true

sysctlImage:
  enabled: false
  command: []
  registry: docker.io
  repository: busybox
  tag: 1.31.1
  pullPolicy: Always
  mountHostSys: false
  resources: {}

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Redis specific configuration options
redis:
  port: 6379
  masterGroupName: "mymaster"       # must match ^[\\w-\\.]+$) and can be templated

  ## Configures redis with tls-port parameter
  # tlsPort: 6385

  ## Configures redis with tls-replication parameter, if true sets "tls-replication yes" in redis.conf
  # tlsReplication: true

  ## It is possible to disable client side certificates authentication when "authClients" is set to "no"
  # authClients: "no"

  # liveness probe parameters for redis container
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    successThreshold: 1
    failureThreshold: 5

  config:
    ## Additional redis conf options can be added below
    ## For all available options see http://download.redis.io/redis-stable/redis.conf
    min-replicas-to-write: 0
    min-replicas-max-lag: 5   # Value in seconds
    maxmemory: "0"       # Max memory to use for each redis instance. Default is unlimited.
    maxmemory-policy: "volatile-lru"  # Max memory policy to use for each redis instance. Default is volatile-lru.
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly: "yes"
    # Disable RDB persistence, AOF persistence already enabled.
    save: ""
    repl-diskless-sync: "no"
    rdbcompression: "no"
    rdbchecksum: "no"
    # Keyspace notifications allow clients to subscribe to Pub/Sub channels in order to receive events affecting the Redis data set in some way. - https://redis.io/topics/notifications
    notify-keyspace-events: AKE
    # Determines if scheduled RDB backups are created. Default is false.
    # Please note that local (on-disk) RDBs will still be created when re-syncing with a new slave. The only way to prevent this is to enable diskless replication.
    #save: "900 1"
    # When enabled, directly sends the RDB over the wire to slaves, without using the disk as intermediate storage. Default is false.
    #repl-diskless-sync: "yes"
    #rdbcompression: "yes"
    #rdbchecksum: "yes"

  ## Custom redis.conf files used to override default settings. If this file is
  ## specified then the redis.config above will be ignored.
  # customConfig: |-
    # Define configuration here

  resources: {}
  #  requests:
  #    memory: 200Mi
  #    cpu: 100m
  #  limits:
  #    memory: 700Mi

  ## Container lifecycle hooks
  ## Ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  lifecycle: {}

## Sentinel specific configuration options
sentinel:
  port: 26379

  ## Configures sentinel with tls-port parameter
  # tlsPort: 26385

  ## Configures sentinel with tls-replication parameter, if true sets "tls-replication yes" in sentinel.conf
  # tlsReplication: true

  ## It is possible to disable client side certificates authentication when "authClients" is set to "no"
  # authClients: "no"

  ## Configures sentinel with AUTH (requirepass params)
  auth: false

  # password: password

  ## Use existing secret containing key `authKey` (ignores sentinel.password)
  # existingSecret: sentinel-secret

  ## Defines the key holding the sentinel password in existing secret.
  authKey: sentinel-password

  # liveness probe parameters for sentinel container
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    successThreshold: 1
    failureThreshold: 5

  quorum: 1
  config:
    ## Additional sentinel conf options can be added below. Only options that
    ## are expressed in the format simialar to 'sentinel xxx mymaster xxx' will
    ## be properly templated expect maxclients option.
    ## For available options see http://download.redis.io/redis-stable/sentinel.conf
    down-after-milliseconds: 10000
    ## Failover timeout value in milliseconds
    failover-timeout: 180000
    parallel-syncs: 5
    maxclients: 10000

  ## Custom sentinel.conf files used to override default settings. If this file is
  ## specified then the sentinel.config above will be ignored.
  # customConfig: |-
    # Define configuration here

  resources: {}
  #  requests:
  #    memory: 200Mi
  #    cpu: 100m
  #  limits:
  #    memory: 200Mi

  ## Container lifecycle hooks
  ## Ref: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  lifecycle: {}

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true

## Node labels, affinity, and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
nodeSelector: {}

## Whether the Redis server pods should be forced to run on separate nodes.
## This is accomplished by setting their AntiAffinity with requiredDuringSchedulingIgnoredDuringExecution as opposed to preferred.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature
##
hardAntiAffinity: true

## Additional affinities to add to the Redis server pods.
##
## Example:
##   nodeAffinity:
##     preferredDuringSchedulingIgnoredDuringExecution:
##       - weight: 50
##         preference:
##           matchExpressions:
##             - key: spot
##               operator: NotIn
##               values:
##                 - "true"
##
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
additionalAffinities: {}

## Override all other affinity settings for the Redis server pods with a string.
##
## Example:
## affinity: |
##   podAntiAffinity:
##     requiredDuringSchedulingIgnoredDuringExecution:
##       - labelSelector:
##           matchLabels:
##             app: {{ template "redis-ha.name" . }}
##             release: {{ .Release.Name }}
##         topologyKey: kubernetes.io/hostname
##     preferredDuringSchedulingIgnoredDuringExecution:
##       - weight: 100
##         podAffinityTerm:
##           labelSelector:
##             matchLabels:
##               app:  {{ template "redis-ha.name" . }}
##               release: {{ .Release.Name }}
##           topologyKey: failure-domain.beta.kubernetes.io/zone
##
affinity: |

# Prometheus exporter specific configuration options
exporter:
  enabled: false
  image: oliver006/redis_exporter
  tag: v1.13.1
  pullPolicy: IfNotPresent

  # prometheus port & scrape path
  port: 9121
  scrapePath: /metrics

  # Address/Host for Redis instance. Default: localhost
  # Exists to circumvent issues with IPv6 dns resolution that occurs on certain environments
  ##
  address: localhost

  ## Set this to true if you want to connect to redis tls port
  # sslEnabled: true

  # cpu/memory resource limits/requests
  resources: {}

  # Additional args for redis exporter
  extraArgs: {}

  # Used to mount a LUA-Script via config map and use it for metrics-collection
  # script: |
  #   -- Example script copied from: https://github.com/oliver006/redis_exporter/blob/master/contrib/sample_collect_script.lua
  #   -- Example collect script for -script option
  #   -- This returns a Lua table with alternating keys and values.
  #   -- Both keys and values must be strings, similar to a HGETALL result.
  #   -- More info about Redis Lua scripting: https://redis.io/commands/eval
  #
  #   local result = {}
  #
  #   -- Add all keys and values from some hash in db 5
  #   redis.call("SELECT", 5)
  #   local r = redis.call("HGETALL", "some-hash-with-stats")
  #   if r ~= nil then
  #   for _,v in ipairs(r) do
  #   table.insert(result, v) -- alternating keys and values
  #   end
  #   end
  #
  #   -- Set foo to 42
  #   table.insert(result, "foo")
  #   table.insert(result, "42") -- note the string, use tostring() if needed
  #
  #   return result

  serviceMonitor:
    # When set true then use a ServiceMonitor to configure scraping
    enabled: false
    # Set the namespace the ServiceMonitor should be deployed
    # namespace: monitoring
    # Set how frequently Prometheus should scrape
    # interval: 30s
    # Set path to redis-exporter telemtery-path
    # telemetryPath: /metrics
    # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
    # labels: {}
    # Set timeout for scrape
    # timeout: 10s

  # prometheus exporter SCANS redis db which can take some time
  # allow different probe settings to not let container crashloop
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 3
    periodSeconds: 15

podDisruptionBudget: {}
  # maxUnavailable: 1
  # minAvailable: 1

## Configures redis with AUTH (requirepass & masterauth conf params)
auth: false
# redisPassword:

## Use existing secret containing key `authKey` (ignores redisPassword)
# existingSecret:

## Defines the key holding the redis password in existing secret.
authKey: auth

persistentVolume:
  enabled: true
  ## redis-ha data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  #storageClass: "managed-premium"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
init:
  resources: {}

# To use a hostPath for data, set persistentVolume.enabled to false
# and define hostPath.path.
# Warning: this might overwrite existing folders on the host system!
hostPath:
  ## path is evaluated as template so placeholders are replaced
  #path: "/data/{{ .Release.Name }}"

  # if chown is true, an init-container with root permissions is launched to
  # change the owner of the hostPath folder to the user defined in the
  # security context
  chown: true

emptyDir: {}

tls:
  ## Fill the name of secret if you want to use your own TLS certificates.
  ## The secret should contains keys named by "tls.certFile" - the certificate, "tls.keyFile" - the private key, "tls.caCertFile" - the certificate of CA and "tls.dhParamsFile" - the dh parameter file
  ## These secret will be genrated using files from certs folder if the secretName is not set and redis.tlsPort is set
  # secretName: tls-secret

  ## Name of certificate file
  certFile: redis.crt
  ## Name of key file
  keyFile: redis.key
  ## Name of Diffie-Hellman (DH) key exchange parameters file
  # dhParamsFile: redis.dh
  ## Name of CA certificate file
  caCertFile: ca.crt

# restore init container is executed if restore.[s3|ssh].source is not false
# restore init container creates /data/dump.rdb_ from original if exists
# restore init container overrides /data/dump.rdb
# secrets are stored into environment of init container - stored encoded on k8s
# REQUIRED for s3 restore: AWS 'access_key' and 'secret_key'
# EXAMPLE source for s3 restore: 's3://bucket/dump.rdb'
# REQUIRED for ssh restore: 'key' should be in one line including CR i.e. '-----BEGIN RSA PRIVATE KEY-----\n...\n...\n...\n-----END RSA PRIVATE KEY-----'
# EXAMPLE source for ssh restore: 'user@server:/path/dump.rdb'
restore:
  timeout: 600
  s3:
    source: false
    access_key: ""
    secret_key: ""
  ssh:
    source: false
    key: ""

**Comment by nunoguerreirorosa** [comment]
From the master node pod within redis-cli sometimes I noticed that the server is closing the connection.

redis-ha-haproxy:6379> keys *
Error: Server closed the connection

**Comment by nunoguerreirorosa** [comment]
I have also attempted to deploy the same setup I have in production but in staging by just changing the hard affinity rule. If I do that everything is deployed in node 1. (3x redis-ha and 3x redis-ha-haproxy). I have noticed that if I create a new redis test client pod in node 0, it wont be able to connect through redis-ha-haproxy, however a test client from node 1 is able to connect through any of the services. revis-ha-haproxy, redis-ha-announce-0,  redis-ha-announce-1,  redis-ha-announce-2.

**Comment by nunoguerreirorosa** [comment]
Sorry about that. I am closing this issue. 

The problem was with the kube-proxy which was not updating correctly the IP tables, so from node 0 accessing a cluster IP service was not able to access the node 1. 

Had to perform a restart...

kubectl rollout restart daemonset kube-proxy -n kube-system
