### ISSUE TITLE
[chart/redis-ha][BUG] Default HAproxy timeout of 30s causes a lot of reconnecting

### ISSUE THREAD

**Issue by japsu** [DandyDeveloper/charts#79]
**Describe the bug**

In `values.yaml`, the `haproxy.timeout.client` and `.server` default to `30s`. Considering Redis connections are relatively long-lived and may be used relatively infrequently, this default seems too low and leads to Redis connections being disconnected due to idle timeout every 30 seconds. Most users of Redis will automatically reconnect, but the disconnect/reconnect cycle is logged, causing lots of noise in the logs.

[Redis documentation on TCP keepalive](https://redis.io/topics/clients#tcp-keepalive) states

>Recent versions of Redis (3.2 or greater) have TCP keepalive (SO_KEEPALIVE socket option) enabled by default and set to about 300 seconds. This option is useful in order to detect dead peers (clients that cannot be reached even if they look connected). Moreover, if there is network equipment between clients and servers that need to see some traffic in order to take the connection open, the option will prevent unexpected connection closed events.

As this is longer than the HAproxy default timeout, it won't help in this occasion.

**Suggested fix**

Raise the default of `haproxy.timeout.client` and `haproxy.timeout.server` to `330s`. Being longer than the Redis default TCP keepalive interval, the keepalives will keep the connections alive.

**To Reproduce**
1. Set up `redis-ha` with `haproxy.enabled: true` without touching timeouts
2. Connect to `redis-ha-haproxy` with a client that logs reconnects and leave it idle
3. Observe the client gets disconnected and reconnects at 30 seconds of idle time

**Expected behavior**

Client connections stay open even if idle.

**Comment by DandyDeveloper** [comment]
@japsu Good suggestion. Doing now.
