### ISSUE TITLE
[chart/redis-ha][BUG]

### ISSUE THREAD

**Issue by pierluigilenoci** [DandyDeveloper/charts#82]
Hello guys,
in the official issue (https://github.com/helm/charts/issues/21103) for the migration from the stable charts the reference to this repo is missing. For clarity I suggest you ask @scottrigby to put you on the list.

**Comment by DandyDeveloper** [comment]
@pierluigilenoci Thank you Pier!

**Comment by pierluigilenoci** [comment]
@DandyDeveloper why closed?

**Comment by pierluigilenoci** [comment]
Never mind, I saw your comment over there.

**Comment by DandyDeveloper** [comment]
@pierluigilenoci Yeah I thought I had done everything, was that not the case?

**Comment by pierluigilenoci** [comment]
Yes yes, sorry. It's all OK.
