### ISSUE TITLE
charts/redis-ha prometheus scraping with service monitoring not working

### ISSUE THREAD

**Issue by RoyKimYYZ** [DandyDeveloper/charts#85]
**Describe the bug**
I have prometheus operator installed in my kubernetes cluster. By simply enabling the metrics and serviceMonitor, I do not see in Prometheus the metrics. 

**To Reproduce**
My configuration is 
metrics:
    enabled: true
    # prometheus port & scrape path
    port: 9101
    portName: http-exporter-port
    scrapePath: /metrics
    ## Metrics exporter pod Annotation and Labels
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9101"
      
    serviceMonitor:
      # When set true then use a ServiceMonitor to configure scraping
      enabled: true
      # Set the namespace the ServiceMonitor should be deployed
      namespace: monitoring
      # Set how frequently Prometheus should scrape
      interval: 30s
      # Set path to redis-exporter telemtery-path
      telemetryPath: /metrics
      # Set labels for the ServiceMonitor, use this to define your scrape label for Prometheus Operator
      labels: {}
      # Set timeout for scrape
      timeout: 10s

**Expected behavior**
See some redis_ metrics show up in prometheus.

**Additional context**
Is there supposed to me a metrics kubernets service? I see this in the bitnami redis helm chart

**Comment by DandyDeveloper** [comment]
@RoyKimYYZ This is a legacy part I havent really tested. I'll get it checked out and fixed. Thank you.

**Comment by RoyKimYYZ** [comment]
@DandyDeveloper  Much appreciated and looking forward to testing it out. I'm preparing for use by the application teams and using StackExchange.Redis with .NET core web applications. Been originally using the bitnami helm chart but I see that this helm chart supports pod failure (e.g. master pod) and recovery and connect to the appropriate master sentinel.

**Comment by nunoguerreirorosa** [comment]
@RoyKimYYZ I have tried it myself and it is working. Maybe you did not enable the exporter?

# Prometheus exporter specific configuration options
exporter:
  enabled: true

**Comment by RoyKimYYZ** [comment]
Thanks I’ll check.
