### ISSUE TITLE
[chart/redis-ha][BUG]

### ISSUE THREAD

**Issue by nunoguerreirorosa** [DandyDeveloper/charts#91]
**Describe the bug**
When installing / upgrading to chart 4.10.9 I am getting an upgrade failed: 

"Error: UPGRADE FAILED: template: redis-ha/templates/redis-ha-announce-service.yaml:51:26: executing "redis-ha/templates/redis-ha-announce-service.yaml" at <.Values.exporter.portName>: can't evaluate field Values in type int"

I have added portName: exporter-port to the values.yaml.

It is related with this commit: 
https://github.com/DandyDeveloper/charts/commit/2387d1614fca5ffffefa1575c02e735b74c91518#diff-acd5d40eb79ed4d6802c58c274eca0ba8c3223045ef2fa0a22949c9b59383b50

Should be probably
{{ $root.Values.exporter.portName }}
instead of {{ .Values.exporter.portName }}

Seems a scoping issue.

**To Reproduce**
1. Install the new chart v4.10.9 with exporter and metrics enabled

**Expected behavior**
Expect the installation to work.

**Comment by DandyDeveloper** [comment]
Taking a look @

**Comment by DandyDeveloper** [comment]
@nunoguerreirorosa Sorry about that, fixed in 4.10.10. Bug in a recent commit I merged from someone elses PR.
